AWSTemplateFormatVersion: "2010-09-09"
Description: 'Project AWS'
Parameters: 
    KeyName:
        Description: Name of an existing KeyPair to enable access to the instance
        Type: AWS::EC2::KeyPair::KeyName
        ConstraintDescription: must be the name of an existing EC2 KeyPair.
    InstanceType:
        Description: WebServer EC2 instance Type
        Type: String
        Default: t2.small
        AllowedValues: [t1.micro, t2.nano, t2.micro, t2.small, t2.medium]
        ConstraintDescription: must be a valid ec2 instance type
    SSHLocation:
        Description: The Ip address range thet can be used to SSH to the EC2 intances
        Type: String
        MinLength: 9
        MaxLength: 18
        Default: 0.0.0.0/0
        AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
        ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x
    LatestAmidId:
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'     
Resources:
    EC2Instance:
        Type: AWS::EC2::Instance
        Properties:
            InstanceType: !Ref 'InstanceType'
            SecurityGroups: [!Ref 'InstanceSecurityGroup']
            KeyName: !Ref 'KeyName'
            ImageId: !Ref 'LatestAmidId'
        DeletionPolicy: Delete
    InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Enable SSH access via port 22
            SecurityGroupIngress:
               - IpProtocol: tcp
                 FromPort: 22
                 ToPort: 22
                 CidrIp: !Ref 'SSHLocation'   
        DeletionPolicy: Delete        
Outputs:
   InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'EC2Instance'
   AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, AvailabilityZone]
   PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicDnsName]
   PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicIp]   
            
            